name: Analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-app:
    runs-on: ubuntu-20.04
    name: Lint app
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.15.4
      - name: Install NPM Packages
        run: npm ci
      - name: Lint
        run: npm run lint

  lint-dockerfile:
    runs-on: ubuntu-20.04
    name: Lint dockerfile
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Lint app dockerfile
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: Dockerfile
      - name: Lint staticman dockerfile
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: staticman/Dockerfile
